version: "3.9"

services:
  duckdb:
    build:
      context: ./db
    working_dir: /app
    volumes:
      - ./db:/app
      - /home/ubuntu/s3:/data:ro
    ports:
      - "9999:9999"

  ml:
    build:
      context: ./model
    working_dir: /app
    volumes:
      - ./model:/app
      - /home/ubuntu/s3:/data:ro
    expose:
      - "5000"            # internal only (no public port)

  dashboard:
    build:
      context: ./dashboard
    working_dir: /app
    volumes:
      - ./dashboard:/app
      - /home/ubuntu/s3:/data:ro
    ports:
      - "8000:8000"
    depends_on:
      - duckdb
      - ml
