version: '3.9'

services:
  duckdb:
    build:
      context: ./db
    volumes:
      - ./db:/app
    working_dir: /app
    ports:
      - "9999:9999"
  ml:
    build: ./model
    ports:
      - "5000:5000"
    
  dashboard:
    build:
      context: ./dashboard
    volumes:
      - ./dashboard:/app
    working_dir: /app
    ports:
      - "5801:8501"
    depends_on:
      - duckdb
      - ml
